
package com.soap.client.model.xmlmodel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.soap.client.generate.*;
import com.soap.client.generate.CreditInfoByIntCodeXMLResponse;
import com.soap.client.generate.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CreditOrgInfoSoap", targetNamespace = "http://web.cbr.ru/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CreditOrgInfoSoap {


    /**
     * 
     *                 ������ �� BIC ����� �� (��� XMLDocument), ��� ��������, ver: 04.07.2007
     *             
     * 
     * @return
     *     returns EnumBICXMLResponse.EnumBICXMLResult
     */
    @WebMethod(operationName = "EnumBIC_XML", action = "http://web.cbr.ru/EnumBIC_XML")
    @WebResult(name = "EnumBIC_XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumBIC_XML", targetNamespace = "http://web.cbr.ru/", className = "EnumBICXML")
    @ResponseWrapper(localName = "EnumBIC_XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "EnumBICXMLResponse")
    public EnumBICXMLResponse.EnumBICXMLResult enumBICXML();

    /**
     * 
     *                 ��������� ������������ ���� ������� �� ������, ver: 22.04.2015
     *             
     * 
     * @param code
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "GetFormsMaxDate", action = "http://web.cbr.ru/GetFormsMaxDate")
    @WebResult(name = "GetFormsMaxDateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetFormsMaxDate", targetNamespace = "http://web.cbr.ru/", className = "GetFormsMaxDate")
    @ResponseWrapper(localName = "GetFormsMaxDateResponse", targetNamespace = "http://web.cbr.ru/", className = "GetFormsMaxDateResponse")
    public XMLGregorianCalendar getFormsMaxDate(
        @WebParam(name = "code", targetNamespace = "http://web.cbr.ru/")
            int code);

    /**
     * ��������� ���� ���������� ���������� ���� �� ��
     *
     * @return
     *     returns javax.xml.datatype.XMLGregorianCalendar
     */
    @WebMethod(operationName = "LastUpdate", action = "http://web.cbr.ru/LastUpdate")
    @WebResult(name = "LastUpdateResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "LastUpdate", targetNamespace = "http://web.cbr.ru/", className = "LastUpdate")
    @ResponseWrapper(localName = "LastUpdateResponse", targetNamespace = "http://web.cbr.ru/", className = "LastUpdateResponse")
    public XMLGregorianCalendar lastUpdate();

    /**
     *
     *                 ������ �� BIC ����� �� (��� DataSet), ��� ��������, ver: 17.03.2015
     *
     *
     * @return
     *     returns EnumBICResponse.EnumBICResult
     */
    @WebMethod(operationName = "EnumBIC", action = "http://web.cbr.ru/EnumBIC")
    @WebResult(name = "EnumBICResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "EnumBIC", targetNamespace = "http://web.cbr.ru/", className = "EnumBIC")
    @ResponseWrapper(localName = "EnumBICResponse", targetNamespace = "http://web.cbr.ru/", className = "EnumBICResponse")
    public EnumBICResponse.EnumBICResult enumBIC();

    /**
     *
     *                 ������ ��. ����� 101 (��� XMLDocument) �� ���������� ��
     *
     *
     * @param indID
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FormExXMLResponse.Data101FormExXMLResult
     */
    @WebMethod(operationName = "Data101FormExXML", action = "http://web.cbr.ru/Data101FormExXML")
    @WebResult(name = "Data101FormExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormExXML", targetNamespace = "http://web.cbr.ru/", className = "Data101FormExXML")
    @ResponseWrapper(localName = "Data101FormExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FormExXMLResponse")
    public Data101FormExXMLResponse.Data101FormExXMLResult data101FormExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
            int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101, ��� �������� (��� DataSet) �� ���������� �� ver 07.03.2017
     *
     *
     * @param indID
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FormExResponse.Data101FormExResult
     */
    @WebMethod(operationName = "Data101FormEx", action = "http://web.cbr.ru/Data101FormEx")
    @WebResult(name = "Data101FormExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormEx", targetNamespace = "http://web.cbr.ru/", className = "Data101FormEx")
    @ResponseWrapper(localName = "Data101FormExResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FormExResponse")
    public Data101FormExResponse.Data101FormExResult data101FormEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
            int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101, ��� �������� (��� XMLDocument)
     *
     *
     * @param indID
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FormXMLResponse.Data101FormXMLResult
     */
    @WebMethod(operationName = "Data101FormXML", action = "http://web.cbr.ru/Data101FormXML")
    @WebResult(name = "Data101FormXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FormXML", targetNamespace = "http://web.cbr.ru/", className = "Data101FormXML")
    @ResponseWrapper(localName = "Data101FormXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FormXMLResponse")
    public Data101FormXMLResponse.Data101FormXMLResult data101FormXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
            int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     * ������ ��. ����� 101, ��� �������� (��� DataSet)
     *
     * @param indID
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FormResponse.Data101FormResult
     */
    @WebMethod(operationName = "Data101Form", action = "http://web.cbr.ru/Data101Form")
    @WebResult(name = "Data101FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101Form", targetNamespace = "http://web.cbr.ru/", className = "Data101Form")
    @ResponseWrapper(localName = "Data101FormResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FormResponse")
    public Data101FormResponse.Data101FormResult data101Form(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndID", targetNamespace = "http://web.cbr.ru/")
            int indID,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     * ������ ��. ����� 101, ��������� (��� XMLDocument)
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FullXMLResponse.Data101FullXMLResult
     */
    @WebMethod(operationName = "Data101FullXML", action = "http://web.cbr.ru/Data101FullXML")
    @WebResult(name = "Data101FullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullXML", targetNamespace = "http://web.cbr.ru/", className = "Data101FullXML")
    @ResponseWrapper(localName = "Data101FullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullXMLResponse")
    public Data101FullXMLResponse.Data101FullXMLResult data101FullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��������, ����� �������, ����������� v2) (��� XMLDocument) �� ���������� ��. ver 17.03.2015
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FullExXMLResponse.Data101FullExXMLResult
     */
    @WebMethod(operationName = "Data101FullExXML", action = "http://web.cbr.ru/Data101FullExXML")
    @WebResult(name = "Data101FullExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExXML", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExXML")
    @ResponseWrapper(localName = "Data101FullExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExXMLResponse")
    public Data101FullExXMLResponse.Data101FullExXMLResult data101FullExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��������, ����� �������, ����������� v2) (��� DataSet) ver 17.03.2015
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FullExResponse.Data101FullExResult
     */
    @WebMethod(operationName = "Data101FullEx", action = "http://web.cbr.ru/Data101FullEx")
    @WebResult(name = "Data101FullExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullEx", targetNamespace = "http://web.cbr.ru/", className = "Data101FullEx")
    @ResponseWrapper(localName = "Data101FullExResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExResponse")
    public Data101FullExResponse.Data101FullExResult data101FullEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��� XML) ver 07.03.2017
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FullExV2XMLResponse.Data101FullExV2XMLResult
     */
    @WebMethod(operationName = "Data101FullExV2XML", action = "http://web.cbr.ru/Data101FullExV2XML")
    @WebResult(name = "Data101FullExV2XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExV2XML", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExV2XML")
    @ResponseWrapper(localName = "Data101FullExV2XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExV2XMLResponse")
    public Data101FullExV2XMLResponse.Data101FullExV2XMLResult data101FullExV2XML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��� DataSet) ver 07.03.2017
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data101FullExV2Response.Data101FullExV2Result
     */
    @WebMethod(operationName = "Data101FullExV2", action = "http://web.cbr.ru/Data101FullExV2")
    @WebResult(name = "Data101FullExV2Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullExV2", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExV2")
    @ResponseWrapper(localName = "Data101FullExV2Response", targetNamespace = "http://web.cbr.ru/", className = "Data101FullExV2Response")
    public Data101FullExV2Response.Data101FullExV2Result data101FullExV2(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (�������, ����������� v2) (��� DataSet)
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FullResponse.Data101FullResult
     */
    @WebMethod(operationName = "Data101Full", action = "http://web.cbr.ru/Data101Full")
    @WebResult(name = "Data101FullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101Full", targetNamespace = "http://web.cbr.ru/", className = "Data101Full")
    @ResponseWrapper(localName = "Data101FullResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullResponse")
    public Data101FullResponse.Data101FullResult data101Full(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            int indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��� XML) mod 07.03.2017
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FullV2XMLResponse.Data101FullV2XMLResult
     */
    @WebMethod(operationName = "Data101FullV2XML", action = "http://web.cbr.ru/Data101FullV2XML")
    @WebResult(name = "Data101FullV2XMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullV2XML", targetNamespace = "http://web.cbr.ru/", className = "Data101FullV2XML")
    @ResponseWrapper(localName = "Data101FullV2XMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data101FullV2XMLResponse")
    public Data101FullV2XMLResponse.Data101FullV2XMLResult data101FullV2XML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 101,��������� (��� DataSet) mod 07.03.2017
     *
     *
     * @param indCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data101FullV2Response.Data101FullV2Result
     */
    @WebMethod(operationName = "Data101FullV2", action = "http://web.cbr.ru/Data101FullV2")
    @WebResult(name = "Data101FullV2Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data101FullV2", targetNamespace = "http://web.cbr.ru/", className = "Data101FullV2")
    @ResponseWrapper(localName = "Data101FullV2Response", targetNamespace = "http://web.cbr.ru/", className = "Data101FullV2Response")
    public Data101FullV2Response.Data101FullV2Result data101FullV2(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "IndCode", targetNamespace = "http://web.cbr.ru/")
            String indCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 102, ������ (��� XMLDocument) �� ���������� ��.
     *
     *
     * @param symbCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data102FormExXMLResponse.Data102FormExXMLResult
     */
    @WebMethod(operationName = "Data102FormExXML", action = "http://web.cbr.ru/Data102FormExXML")
    @WebResult(name = "Data102FormExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormExXML", targetNamespace = "http://web.cbr.ru/", className = "Data102FormExXML")
    @ResponseWrapper(localName = "Data102FormExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data102FormExXMLResponse")
    public Data102FormExXMLResponse.Data102FormExXMLResult data102FormExXML(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
            int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ������ ��. ����� 102 (��� DataSet) �� ���������� ��. ver 24.06.2014
     *
     *
     * @param symbCode
     * @param dateTo
     * @param credorgNumbers
     * @param dateFrom
     * @return
     *     returns Data102FormExResponse.Data102FormExResult
     */
    @WebMethod(operationName = "Data102FormEx", action = "http://web.cbr.ru/Data102FormEx")
    @WebResult(name = "Data102FormExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormEx", targetNamespace = "http://web.cbr.ru/", className = "Data102FormEx")
    @ResponseWrapper(localName = "Data102FormExResponse", targetNamespace = "http://web.cbr.ru/", className = "Data102FormExResponse")
    public Data102FormExResponse.Data102FormExResult data102FormEx(
        @WebParam(name = "CredorgNumbers", targetNamespace = "http://web.cbr.ru/")
            ArrayOfAnyType credorgNumbers,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
            int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     * ������ ��. ����� 102, ������ (��� XMLDocument)
     *
     * @param symbCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data102FormXMLResponse.Data102FormXMLResult
     */
    @WebMethod(operationName = "Data102FormXML", action = "http://web.cbr.ru/Data102FormXML")
    @WebResult(name = "Data102FormXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102FormXML", targetNamespace = "http://web.cbr.ru/", className = "Data102FormXML")
    @ResponseWrapper(localName = "Data102FormXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data102FormXMLResponse")
    public Data102FormXMLResponse.Data102FormXMLResult data102FormXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
            int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     * ������ ��. ����� 102 (��� DataSet)
     *
     * @param symbCode
     * @param dateTo
     * @param credorgNumber
     * @param dateFrom
     * @return
     *     returns Data102FormResponse.Data102FormResult
     */
    @WebMethod(operationName = "Data102Form", action = "http://web.cbr.ru/Data102Form")
    @WebResult(name = "Data102FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data102Form", targetNamespace = "http://web.cbr.ru/", className = "Data102Form")
    @ResponseWrapper(localName = "Data102FormResponse", targetNamespace = "http://web.cbr.ru/", className = "Data102FormResponse")
    public Data102FormResponse.Data102FormResult data102Form(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "SymbCode", targetNamespace = "http://web.cbr.ru/")
            int symbCode,
        @WebParam(name = "DateFrom", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateFrom,
        @WebParam(name = "DateTo", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar dateTo);

    /**
     *
     *                 ���������� �������� ��� ����� 102 (��� XMLDocument)
     *
     *
     * @return
     *     returns Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult
     */
    @WebMethod(operationName = "Form102IndicatorsEnumXML", action = "http://web.cbr.ru/Form102IndicatorsEnumXML")
    @WebResult(name = "Form102IndicatorsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form102IndicatorsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "Form102IndicatorsEnumXML")
    @ResponseWrapper(localName = "Form102IndicatorsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Form102IndicatorsEnumXMLResponse")
    public Form102IndicatorsEnumXMLResponse.Form102IndicatorsEnumXMLResult form102IndicatorsEnumXML();

    /**
     * ���������� �������� ��� ����� 102 (��� DataSet)
     *
     * @return
     *     returns Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult
     */
    @WebMethod(operationName = "Form102IndicatorsEnum", action = "http://web.cbr.ru/Form102IndicatorsEnum")
    @WebResult(name = "Form102IndicatorsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form102IndicatorsEnum", targetNamespace = "http://web.cbr.ru/", className = "Form102IndicatorsEnum")
    @ResponseWrapper(localName = "Form102IndicatorsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "Form102IndicatorsEnumResponse")
    public Form102IndicatorsEnumResponse.Form102IndicatorsEnumResult form102IndicatorsEnum();

    /**
     *
     *                 ���������� ����������� ��� ����� 101 (��� XMLDocument)
     *
     *
     * @return
     *     returns Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult
     */
    @WebMethod(operationName = "Form101IndicatorsEnumXML", action = "http://web.cbr.ru/Form101IndicatorsEnumXML")
    @WebResult(name = "Form101IndicatorsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form101IndicatorsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "Form101IndicatorsEnumXML")
    @ResponseWrapper(localName = "Form101IndicatorsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Form101IndicatorsEnumXMLResponse")
    public Form101IndicatorsEnumXMLResponse.Form101IndicatorsEnumXMLResult form101IndicatorsEnumXML();

    /**
     * ���������� ����������� ��� ����� 101 (��� DataSet)
     *
     * @return
     *     returns Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult
     */
    @WebMethod(operationName = "Form101IndicatorsEnum", action = "http://web.cbr.ru/Form101IndicatorsEnum")
    @WebResult(name = "Form101IndicatorsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Form101IndicatorsEnum", targetNamespace = "http://web.cbr.ru/", className = "Form101IndicatorsEnum")
    @ResponseWrapper(localName = "Form101IndicatorsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "Form101IndicatorsEnumResponse")
    public Form101IndicatorsEnumResponse.Form101IndicatorsEnumResult form101IndicatorsEnum();

    /**
     * ��������������� ����� �� ���������� ��� ��.
     *
     * @param regNumber
     * @return
     *     returns double
     */
    @WebMethod(operationName = "RegNumToIntCode", action = "http://web.cbr.ru/RegNumToIntCode")
    @WebResult(name = "RegNumToIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegNumToIntCode", targetNamespace = "http://web.cbr.ru/", className = "RegNumToIntCode")
    @ResponseWrapper(localName = "RegNumToIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "RegNumToIntCodeResponse")
    public double regNumToIntCode(
        @WebParam(name = "RegNumber", targetNamespace = "http://web.cbr.ru/")
            double regNumber);

    /**
     *
     *                 ���������� ��� ����.���. � ��������������� ����� ��.
     *
     *
     * @param intNumber
     * @return
     *     returns double
     */
    @WebMethod(operationName = "IntCodeToRegNum", action = "http://web.cbr.ru/IntCodeToRegNum")
    @WebResult(name = "IntCodeToRegNumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "IntCodeToRegNum", targetNamespace = "http://web.cbr.ru/", className = "IntCodeToRegNum")
    @ResponseWrapper(localName = "IntCodeToRegNumResponse", targetNamespace = "http://web.cbr.ru/", className = "IntCodeToRegNumResponse")
    public double intCodeToRegNum(
        @WebParam(name = "IntNumber", targetNamespace = "http://web.cbr.ru/")
            double intNumber);

    /**
     * Bic ��� �� ���������� ��� ����.���.
     *
     * @param bicCode
     * @return
     *     returns double
     */
    @WebMethod(operationName = "BicToIntCode", action = "http://web.cbr.ru/BicToIntCode")
    @WebResult(name = "BicToIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BicToIntCode", targetNamespace = "http://web.cbr.ru/", className = "BicToIntCode")
    @ResponseWrapper(localName = "BicToIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "BicToIntCodeResponse")
    public double bicToIntCode(
        @WebParam(name = "BicCode", targetNamespace = "http://web.cbr.ru/")
            String bicCode);

    /**
     * Bic ��� � ��������������� ����� ����.���.
     *
     * @param bicCode
     * @return
     *     returns int
     */
    @WebMethod(operationName = "BicToRegNumber", action = "http://web.cbr.ru/BicToRegNumber")
    @WebResult(name = "BicToRegNumberResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "BicToRegNumber", targetNamespace = "http://web.cbr.ru/", className = "BicToRegNumber")
    @ResponseWrapper(localName = "BicToRegNumberResponse", targetNamespace = "http://web.cbr.ru/", className = "BicToRegNumberResponse")
    public int bicToRegNumber(
        @WebParam(name = "BicCode", targetNamespace = "http://web.cbr.ru/")
            String bicCode);

    /**
     * ���������� �������� (��� DataSet)
     *
     * @return
     *     returns RegionsEnumResponse.RegionsEnumResult
     */
    @WebMethod(operationName = "RegionsEnum", action = "http://web.cbr.ru/RegionsEnum")
    @WebResult(name = "RegionsEnumResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegionsEnum", targetNamespace = "http://web.cbr.ru/", className = "RegionsEnum")
    @ResponseWrapper(localName = "RegionsEnumResponse", targetNamespace = "http://web.cbr.ru/", className = "RegionsEnumResponse")
    public RegionsEnumResponse.RegionsEnumResult regionsEnum();

    /**
     *
     *                 ���������� �������� (��� XMLDocument), ver- 18.01.2007
     *
     *
     * @return
     *     returns RegionsEnumXMLResponse.RegionsEnumXMLResult
     */
    @WebMethod(operationName = "RegionsEnumXML", action = "http://web.cbr.ru/RegionsEnumXML")
    @WebResult(name = "RegionsEnumXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "RegionsEnumXML", targetNamespace = "http://web.cbr.ru/", className = "RegionsEnumXML")
    @ResponseWrapper(localName = "RegionsEnumXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "RegionsEnumXMLResponse")
    public RegionsEnumXMLResponse.RegionsEnumXMLResult regionsEnumXML();

    /**
     *
     *                 ����� ��������� ���. �� �������(����) (��� DataSet)
     *
     *
     * @param regCode
     * @return
     *     returns SearchByRegionCodeResponse.SearchByRegionCodeResult
     */
    @WebMethod(operationName = "SearchByRegionCode", action = "http://web.cbr.ru/SearchByRegionCode")
    @WebResult(name = "SearchByRegionCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByRegionCode", targetNamespace = "http://web.cbr.ru/", className = "SearchByRegionCode")
    @ResponseWrapper(localName = "SearchByRegionCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "SearchByRegionCodeResponse")
    public SearchByRegionCodeResponse.SearchByRegionCodeResult searchByRegionCode(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
            int regCode);

    /**
     * ����� ��������� ���. �� �������(����) (��� XML)
     *
     * @param regCode
     * @return
     *     returns SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult
     */
    @WebMethod(operationName = "SearchByRegionCodeXML", action = "http://web.cbr.ru/SearchByRegionCodeXML")
    @WebResult(name = "SearchByRegionCodeXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByRegionCodeXML", targetNamespace = "http://web.cbr.ru/", className = "SearchByRegionCodeXML")
    @ResponseWrapper(localName = "SearchByRegionCodeXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "SearchByRegionCodeXMLResponse")
    public SearchByRegionCodeXMLResponse.SearchByRegionCodeXMLResult searchByRegionCodeXML(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
            int regCode);

    /**
     * ����� ��������� ���. �� �������� (��� XML)
     *
     * @param namePart
     * @return
     *     returns SearchByNameXMLResponse.SearchByNameXMLResult
     */
    @WebMethod(operationName = "SearchByNameXML", action = "http://web.cbr.ru/SearchByNameXML")
    @WebResult(name = "SearchByNameXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByNameXML", targetNamespace = "http://web.cbr.ru/", className = "SearchByNameXML")
    @ResponseWrapper(localName = "SearchByNameXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "SearchByNameXMLResponse")
    public SearchByNameXMLResponse.SearchByNameXMLResult searchByNameXML(
        @WebParam(name = "NamePart", targetNamespace = "http://web.cbr.ru/")
            String namePart);

    /**
     * ����� ��������� ���. �� �������� (��� DataSet)
     *
     * @param namePart
     * @return
     *     returns SearchByNameResponse.SearchByNameResult
     */
    @WebMethod(operationName = "SearchByName", action = "http://web.cbr.ru/SearchByName")
    @WebResult(name = "SearchByNameResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "SearchByName", targetNamespace = "http://web.cbr.ru/", className = "SearchByName")
    @ResponseWrapper(localName = "SearchByNameResponse", targetNamespace = "http://web.cbr.ru/", className = "SearchByNameResponse")
    public SearchByNameResponse.SearchByNameResult searchByName(
        @WebParam(name = "NamePart", targetNamespace = "http://web.cbr.ru/")
            String namePart);

    /**
     *
     *                 ���������� � ��������� ���. �� ��.���� (��� XMLDocument)
     *
     *
     * @param internalCode
     * @return
     *     returns CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeXML", action = "http://web.cbr.ru/CreditInfoByIntCodeXML")
    @WebResult(name = "CreditInfoByIntCodeXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeXML", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeXML")
    @ResponseWrapper(localName = "CreditInfoByIntCodeXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeXMLResponse")
    public CreditInfoByIntCodeXMLResponse.CreditInfoByIntCodeXMLResult creditInfoByIntCodeXML(
        @WebParam(name = "InternalCode", targetNamespace = "http://web.cbr.ru/")
            double internalCode);

    /**
     *
     *                 ���������� � ��������� ���. �� ��.���� (��� XML Document) ver- 26.02.2015
     *
     *
     * @param internalCodes
     * @return
     *     returns CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeExXML", action = "http://web.cbr.ru/CreditInfoByIntCodeExXML")
    @WebResult(name = "CreditInfoByIntCodeExXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeExXML", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeExXML")
    @ResponseWrapper(localName = "CreditInfoByIntCodeExXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeExXMLResponse")
    public CreditInfoByIntCodeExXMLResponse.CreditInfoByIntCodeExXMLResult creditInfoByIntCodeExXML(
        @WebParam(name = "InternalCodes", targetNamespace = "http://web.cbr.ru/")
            ArrayOfDouble internalCodes);

    /**
     *
     *                 ���������� � ��������� ���. �� ��.���� (��� DataSet) ver- 03.03.2015
     *
     *
     * @param internalCodes
     * @return
     *     returns CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult
     */
    @WebMethod(operationName = "CreditInfoByIntCodeEx", action = "http://web.cbr.ru/CreditInfoByIntCodeEx")
    @WebResult(name = "CreditInfoByIntCodeExResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCodeEx", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeEx")
    @ResponseWrapper(localName = "CreditInfoByIntCodeExResponse", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeExResponse")
    public CreditInfoByIntCodeExResponse.CreditInfoByIntCodeExResult creditInfoByIntCodeEx(
        @WebParam(name = "InternalCodes", targetNamespace = "http://web.cbr.ru/")
            ArrayOfDouble internalCodes);

    /**
     *
     *                 ���������� � ��������� ���. �� ��.���� (��� DataSet) ver- 11.01.2007
     *
     *
     * @param internalCode
     * @return
     *     returns CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult
     */
    @WebMethod(operationName = "CreditInfoByIntCode", action = "http://web.cbr.ru/CreditInfoByIntCode")
    @WebResult(name = "CreditInfoByIntCodeResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "CreditInfoByIntCode", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCode")
    @ResponseWrapper(localName = "CreditInfoByIntCodeResponse", targetNamespace = "http://web.cbr.ru/", className = "CreditInfoByIntCodeResponse")
    public CreditInfoByIntCodeResponse.CreditInfoByIntCodeResult creditInfoByIntCode(
        @WebParam(name = "InternalCode", targetNamespace = "http://web.cbr.ru/")
            double internalCode);

    /**
     *
     *                 ���������� �� ���������� ���� ��������� ���. �� ��.���� (��� DataSet), ver- 18.01.2007
     *
     *
     * @param intCode
     * @return
     *     returns GetOfficesResponse.GetOfficesResult
     */
    @WebMethod(operationName = "GetOffices", action = "http://web.cbr.ru/GetOffices")
    @WebResult(name = "GetOfficesResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOffices", targetNamespace = "http://web.cbr.ru/", className = "GetOffices")
    @ResponseWrapper(localName = "GetOfficesResponse", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesResponse")
    public GetOfficesResponse.GetOfficesResult getOffices(
        @WebParam(name = "IntCode", targetNamespace = "http://web.cbr.ru/")
            double intCode);

    /**
     *
     *                 ���������� �� ���������� ���� ��������� ���. �� ������� (����) (��� DataSet), ver- 18.01.2007
     *
     *
     * @param regCode
     * @return
     *     returns GetOfficesByRegionResponse.GetOfficesByRegionResult
     */
    @WebMethod(operationName = "GetOfficesByRegion", action = "http://web.cbr.ru/GetOfficesByRegion")
    @WebResult(name = "GetOfficesByRegionResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesByRegion", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesByRegion")
    @ResponseWrapper(localName = "GetOfficesByRegionResponse", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesByRegionResponse")
    public GetOfficesByRegionResponse.GetOfficesByRegionResult getOfficesByRegion(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
            int regCode);

    /**
     *
     *                 ���������� �� ���������� ���� ��������� ���. �� ��.���� (��� XML)
     *
     *
     * @param intCode
     * @return
     *     returns GetOfficesXMLResponse.GetOfficesXMLResult
     */
    @WebMethod(operationName = "GetOfficesXML", action = "http://web.cbr.ru/GetOfficesXML")
    @WebResult(name = "GetOfficesXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesXML", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesXML")
    @ResponseWrapper(localName = "GetOfficesXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesXMLResponse")
    public GetOfficesXMLResponse.GetOfficesXMLResult getOfficesXML(
        @WebParam(name = "IntCode", targetNamespace = "http://web.cbr.ru/")
            double intCode);

    /**
     *
     *                 ���������� �� ���������� ���� ��������� ���. �� ������� (����) (��� XML), ver- 18.01.2007
     *
     *
     * @param regCode
     * @return
     *     returns GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult
     */
    @WebMethod(operationName = "GetOfficesByRegionXML", action = "http://web.cbr.ru/GetOfficesByRegionXML")
    @WebResult(name = "GetOfficesByRegionXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetOfficesByRegionXML", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesByRegionXML")
    @ResponseWrapper(localName = "GetOfficesByRegionXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "GetOfficesByRegionXMLResponse")
    public GetOfficesByRegionXMLResponse.GetOfficesByRegionXMLResult getOfficesByRegionXML(
        @WebParam(name = "RegCode", targetNamespace = "http://web.cbr.ru/")
            int regCode);

    /**
     * ������ �� ����� 134 (��� XML)
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data134FormFullXMLResponse.Data134FormFullXMLResult
     */
    @WebMethod(operationName = "Data134FormFullXML", action = "http://web.cbr.ru/Data134FormFullXML")
    @WebResult(name = "Data134FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data134FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "Data134FormFullXML")
    @ResponseWrapper(localName = "Data134FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data134FormFullXMLResponse")
    public Data134FormFullXMLResponse.Data134FormFullXMLResult data134FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

    /**
     * ������ �� ����� 134, OLAP, (��� DataSet)
     *
     * @param fromDate
     * @param code
     * @param toDate
     * @param credorgNumber
     * @return
     *     returns Olap134FormResponse.Olap134FormResult
     */
    @WebMethod(operationName = "Olap134Form", action = "http://web.cbr.ru/Olap134Form")
    @WebResult(name = "Olap134FormResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Olap134Form", targetNamespace = "http://web.cbr.ru/", className = "Olap134Form")
    @ResponseWrapper(localName = "Olap134FormResponse", targetNamespace = "http://web.cbr.ru/", className = "Olap134FormResponse")
    public Olap134FormResponse.Olap134FormResult olap134Form(
        @WebParam(name = "Code", targetNamespace = "http://web.cbr.ru/")
            String code,
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "FromDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar fromDate,
        @WebParam(name = "ToDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar toDate);

    /**
     * ������ �� ����� 135 (��� DataSet) ver 05.06.2014
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data135FormFullResponse.Data135FormFullResult
     */
    @WebMethod(operationName = "Data135FormFull", action = "http://web.cbr.ru/Data135FormFull")
    @WebResult(name = "Data135FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data135FormFull", targetNamespace = "http://web.cbr.ru/", className = "Data135FormFull")
    @ResponseWrapper(localName = "Data135FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "Data135FormFullResponse")
    public Data135FormFullResponse.Data135FormFullResult data135FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

    /**
     * ������ �� ����� 135 (��� XML)
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data135FormFullXMLResponse.Data135FormFullXMLResult
     */
    @WebMethod(operationName = "Data135FormFullXML", action = "http://web.cbr.ru/Data135FormFullXML")
    @WebResult(name = "Data135FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data135FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "Data135FormFullXML")
    @ResponseWrapper(localName = "Data135FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data135FormFullXMLResponse")
    public Data135FormFullXMLResponse.Data135FormFullXMLResult data135FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

    /**
     * ������ �� ����� 123 (��� DataSet)
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data123FormFullResponse.Data123FormFullResult
     */
    @WebMethod(operationName = "Data123FormFull", action = "http://web.cbr.ru/Data123FormFull")
    @WebResult(name = "Data123FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data123FormFull", targetNamespace = "http://web.cbr.ru/", className = "Data123FormFull")
    @ResponseWrapper(localName = "Data123FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "Data123FormFullResponse")
    public Data123FormFullResponse.Data123FormFullResult data123FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

    /**
     * ������ �� ����� 123 (��� XML)
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data123FormFullXMLResponse.Data123FormFullXMLResult
     */
    @WebMethod(operationName = "Data123FormFullXML", action = "http://web.cbr.ru/Data123FormFullXML")
    @WebResult(name = "Data123FormFullXMLResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data123FormFullXML", targetNamespace = "http://web.cbr.ru/", className = "Data123FormFullXML")
    @ResponseWrapper(localName = "Data123FormFullXMLResponse", targetNamespace = "http://web.cbr.ru/", className = "Data123FormFullXMLResponse")
    public Data123FormFullXMLResponse.Data123FormFullXMLResult data123FormFullXML(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

    /**
     * ������ ��� ��� ����� 123
     *
     * @param credprgNumber
     * @return
     *     returns ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF123", action = "http://web.cbr.ru/GetDatesForF123")
    @WebResult(name = "GetDatesForF123Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF123", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF123")
    @ResponseWrapper(localName = "GetDatesForF123Response", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF123Response")
    public ArrayOfDateTime getDatesForF123(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
            int credprgNumber);

    /**
     * ������ ��� ��� ����� 101
     *
     * @param credprgNumber
     * @return
     *     returns ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF101", action = "http://web.cbr.ru/GetDatesForF101")
    @WebResult(name = "GetDatesForF101Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF101", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF101")
    @ResponseWrapper(localName = "GetDatesForF101Response", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF101Response")
    public ArrayOfDateTime getDatesForF101(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
            int credprgNumber);

    /**
     * ������ ��� ��� ����� 102
     *
     * @param credprgNumber
     * @return
     *     returns ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF102", action = "http://web.cbr.ru/GetDatesForF102")
    @WebResult(name = "GetDatesForF102Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF102", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF102")
    @ResponseWrapper(localName = "GetDatesForF102Response", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF102Response")
    public ArrayOfDateTime getDatesForF102(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
            int credprgNumber);

    /**
     * ������ ��� ��� ����� 134
     *
     * @param credprgNumber
     * @return
     *     returns ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF134", action = "http://web.cbr.ru/GetDatesForF134")
    @WebResult(name = "GetDatesForF134Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF134", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF134")
    @ResponseWrapper(localName = "GetDatesForF134Response", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF134Response")
    public ArrayOfDateTime getDatesForF134(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
            int credprgNumber);

    /**
     * ������ ��� ��� ����� 135
     *
     * @param credprgNumber
     * @return
     *     returns ArrayOfDateTime
     */
    @WebMethod(operationName = "GetDatesForF135", action = "http://web.cbr.ru/GetDatesForF135")
    @WebResult(name = "GetDatesForF135Result", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "GetDatesForF135", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF135")
    @ResponseWrapper(localName = "GetDatesForF135Response", targetNamespace = "http://web.cbr.ru/", className = "GetDatesForF135Response")
    public ArrayOfDateTime getDatesForF135(
        @WebParam(name = "CredprgNumber", targetNamespace = "http://web.cbr.ru/")
            int credprgNumber);

    /**
     *
     *                 ������ �� ����� 134 - ����������, ������ �� 2015 �. (��� DataSet)
     *
     *
     * @param onDate
     * @param credorgNumber
     * @return
     *     returns Data134FormFullResponse.Data134FormFullResult
     */
    @WebMethod(operationName = "Data134FormFull", action = "http://web.cbr.ru/Data134FormFull")
    @WebResult(name = "Data134FormFullResult", targetNamespace = "http://web.cbr.ru/")
    @RequestWrapper(localName = "Data134FormFull", targetNamespace = "http://web.cbr.ru/", className = "Data134FormFull")
    @ResponseWrapper(localName = "Data134FormFullResponse", targetNamespace = "http://web.cbr.ru/", className = "Data134FormFullResponse")
    public Data134FormFullResponse.Data134FormFullResult data134FormFull(
        @WebParam(name = "CredorgNumber", targetNamespace = "http://web.cbr.ru/")
            int credorgNumber,
        @WebParam(name = "OnDate", targetNamespace = "http://web.cbr.ru/")
            XMLGregorianCalendar onDate);

}
